### ISSUE TITLE
Retrieving the runtime variable type in Java instrumentation

### ISSUE THREAD

**Issue by llmhyy** [code-philia/microbat#4]
As described.

TODO.

**Comment by llmhyy** [comment]
better to have a test case and description of the issue.

**Comment by HongshuW** [comment]
Add valid variable value in virtual variables created by constructors (`<TYPE>_instance`)

**Cli 11: step 77 PrintWriter PrintWriter_instance**
add value for `PrintWriter_instance`

**Comment by HongshuW** [comment]
**Cli 18: step 360 CommandLine cl**
	incorrect variable value
	cl.toString: {args:[-btoast], options:[...]}

**Comment by HongshuW** [comment]
**Cli 18**
After updating instrumentation, the variable value of CommandLine instance is displayed:
<img width="447" alt="Screenshot 2024-08-07 at 2 01 35 PM" src="https://github.com/user-attachments/assets/7058ae14-be72-4b3f-a467-27e4ae29f8e8">

**Comment by HongshuW** [comment]
**Cli 14: step 2119 Parser parser**
