### ISSUE TITLE
Static Analysis of Definition Inference

### ISSUE THREAD

**Issue by Weiyu-Kong** [code-philia/microbat#53]
#### Observation ####
In " microbat.tracerecov.executionsimulator.ExecutionSimulator.estimateComplication( )", we have the input:
- codeLine: ans.add(i + 1);
- rootVar: { "java.util.ArrayList | ans" : "[0]" }
- targetVarName: size
- invokedMethods:
    - java.lang.Integer#valueOf(I)Ljava/lang/Integer;
    - java.util.List#add(Ljava/lang/Object;)Z

but it seems that this method (estimateComplication( )) only checks the first item of invokedMethods which is "java.lang.Integer#valueOf(I)Ljava/lang/Integer;" and return "GUARANTEE_NO_WRITE" after executing " candidateVarVerifier.getVarWriteStatus("size", "java.lang.Integer") ".
![image](https://github.com/user-attachments/assets/846ac9a3-21df-496a-bdaf-6df8bc4f2bc9)

Besides, when we check the method "java.util.List#add(Ljava/lang/Object;)Z" ("List" instead of "ArrayList"), the cfg will not be constructed ( cfg == null ) and the method returns "NO_GUARANTEE".

#### Possible solutions ####
1. Consider all invoked methods
    - GUARANTEE_WRITE has the highest priority which means if there is a method leads to GUARANTEE_WRITE , the result is GUARANTEE_WRITE .
    - And probably GUARANTEE_WRITE > NO_GUARANTEE > GUARANTEE_NO_WRITE.
2. Transfer from base class to derived class to successfully construct cfg ("List" --> "ArrayList").

**Comment by HongshuW** [comment]
Fixed by 498d9667d12eeddf2d97f6ca39dd1fbf12a29453
